"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[╭─](bold #9A348E)\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$jobs\
$os\
$container\
$shell\
$fill\
$all\
$line_break\
[╰─](bold #9A348E)\
$character\
$status\
$sudo\
"""

[fill]
symbol = ' '

[direnv]
disabled = true

[package]
disabled = true

[character]
success_symbol = '[](bold #86BBD8)'
error_symbol = '[](bold #DA627D)'

[cmd_duration]
format = ' [ $duration](bold #FCA17D) '
show_milliseconds = true

[directory]
truncation_symbol = ''
read_only = " "
style = 'bold #DA627D'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[ $branch](bold #FCA17D)'

[git_status]
style = 'bold #FCA17D'

[status]
disabled = false
format = '[$status](bold #DA627D) '

[sudo]
disabled = false
format = '[ sudo: ](bold #DA627D)'

[username]
show_always = true
style_user = "bold #9A348E"
style_root = "bold #9A348E"
format = '[$user]($style) '

[os]
disabled = true

[docker_context]
format = ' [ $context](bold #06969A) '

[c]
format = '[ ($version)](bold #86BBD8)'

[cpp]
format = '[ ($version)](bold #86BBD8)'

[elixir]
format = '[ ($version)](bold #86BBD8)'

[elm]
format = '[ ($version)](bold #86BBD8)'

[golang]
format = '[ $version](bold #86BBD8)'

[gradle]
format = '[ ($version)](bold #86BBD8)'

[haskell]
format = '[ ($version)](bold #86BBD8)'

[java]
format = '[ ${version}](bold #86BBD8)'

[julia]
format = '[ ($version)](bold #86BBD8)'

[nodejs]
format = ' [ ($version)](bold #86BBD8) '

[nim]
format = '[󰆥 ($version)](bold #86BBD8)'

[rust]
format = ' [ $version](bold #86BBD8) '

[scala]
format = '[ ($version)](bold #86BBD8)'

[time]
disabled = false
time_format = "%R"
style = "bold #33658A"
format = '[ ♥ $time ]($style)'
